BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
BOOTLOADER = qmk-dfu
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
# Space reduction https://docs.qmk.fm/#/squeezing_avr
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
